-- ══════════════════════════════════════════════════════════════
-- AI Pneumonia Detection — MySQL Schema
-- ══════════════════════════════════════════════════════════════
-- NOTE: The app uses SQLite by default (no setup needed).
-- Use this file only if you switch to MySQL.
-- ══════════════════════════════════════════════════════════════

CREATE DATABASE IF NOT EXISTS pneumonia_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE pneumonia_db;

-- Users table
CREATE TABLE IF NOT EXISTS users (
    id           INT AUTO_INCREMENT PRIMARY KEY,
    username     VARCHAR(80)  NOT NULL UNIQUE,
    email        VARCHAR(120) NOT NULL UNIQUE,
    password_hash VARCHAR(256) NOT NULL,
    role         VARCHAR(20)  NOT NULL DEFAULT 'user',
    created_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Predictions table
CREATE TABLE IF NOT EXISTS predictions (
    id               INT AUTO_INCREMENT PRIMARY KEY,
    user_id          INT          NOT NULL,
    patient_name     VARCHAR(120) NOT NULL,
    age              INT,
    gender           VARCHAR(10),
    image_path       VARCHAR(255) NOT NULL,
    prediction       VARCHAR(20)  NOT NULL,
    confidence       FLOAT        NOT NULL,
    normal_prob      FLOAT        NOT NULL,
    pneumonia_prob   FLOAT        NOT NULL,
    prediction_date  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Default admin (password: Admin@123)
-- Hash generated by werkzeug.security.generate_password_hash
INSERT IGNORE INTO users (username, email, password_hash, role) VALUES
('admin', 'admin@pneumonia.ai',
 'scrypt:32768:8:1$placeholder$hash_will_be_set_by_flask',
 'admin');
